server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

mybatis:
  # XML扫描路径
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  # 通用Mapper的方法会自动转换驼峰，但手写的SQL需要开启才能转换
  configuration:
    map-underscore-to-camel-case: on

# 打印SQL
logging:
  level:
    com.flyin.example: debug
